#!/usr/bin/env bash
# Script that configures Nginx with a 301 redirect

apt-get update -y

apt-get install nginx -y

echo "Holberton School for the win!" > /var/www/html/index.html

sudo sed -i '/listen 80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

service nginx restart
